### ISSUE TITLE
Question regarding small implementation detail

### ISSUE THREAD

**Issue by Breakend** [kolesarm/Robust-Small-Sample-Standard-Errors#1]
Hi,

I was re-implementing this method and kept getting slight inconsistencies from the package. It appears that the discrepancy is at lines: https://github.com/kolesarm/Robust-Small-Sample-Standard-Errors/blob/master/R/ols.R#L104-L107

It appears that the clustervar is out of order and so it doesn't properly do the correct matrix multiplication, that is u and AQ become out of order such that they don't associate with the right values. I *think* this is a hacky solution to fix it. Empirically, the standard errors I get from this seem more in line (though not totally consistent) with if I didn't use the QR decomposition approach, but just the standard (less efficient) matrix multiplication.

Please let me know if that makes sense and if my solution seems correct. Perhaps I am misunderstanding the code.

Thanks!!

Proposed "fix": 

```
uf <- function(s) {
    stuff <- as.matrix(u[clustervar==s, drop=FALSE])
    stuff
}


new.cluster.var <- function(s) {
    stuff <- length(u[clustervar==s, drop=FALSE])
    as.matrix(rep(s, stuff))
}


ls <- levels(clustervar)
AQ <- lapply(ls, AQf) # list of matrices
us <- lapply(ls, uf) 
clusters <- lapply(ls, new.cluster.var)
AQ <- do.call(rbind, AQ)
new.u  <- do.call(rbind, us)
clusters <- do.call(rbind, clusters)

intermediate <- as.vector(new.u)*AQ
uj <- apply(intermediate, 2, function(x) tapply(x, as.factor(clusters), sum))
HC2 <- crossprod(uj)
```

For a test dataset here are the values I get:

| |   const. |  b1.  |        b2 |        b3 |
| ----------- | ----------- | -----------  | -----------  | ----------- |
|  se non-QR ("true") | 0.8804 | 0.0042 | 0.0645 | 0.0088 |
|  package as is | 0.5952 | 0.0002 | 0.0482 | 0.0077 |
|  package with replacement code | 0.837842087 | 0.004401259 | 0.057727105 | 0.008641744|

**Comment by kolesarm** [comment]
Thank you for pointing out this issue! You're correct, the package incorrectly assumed that the data set is ordered by cluster, which affects both the HC2 variance compuation, and the degrees of freedom adjustment. The commit [#0e81199](https://github.com/kolesarm/Robust-Small-Sample-Standard-Errors/commit/0e81199d82c15811e822acc0b8649e3303ebe75d) should fix it, see [lines 93-97](https://github.com/kolesarm/Robust-Small-Sample-Standard-Errors/blob/master/R/ols.R#L93-L97). Let me know if this doesn't resolve your issue
