### ISSUE TITLE
Speed-up by using collapse::fsum

### ISSUE THREAD

**Issue by skranz** [kolesarm/Robust-Small-Sample-Standard-Errors#3]
Hi Michal,

thanks a lot for your great package! While adapting and profiling your code to perform at some point fast large meta-studies about different cluster-robust standard errors, I found that a simple change can substantially speed-up your code. Here is an example implementation: https://github.com/skranz/dfadjustFaster. There is a roughly 10x speed increase in the example in the README.md. 

The modification is very simple: replace the `tapply(x, clustervariable, sum)` and `apply(some_matrix,2,tapply(x,clustervaiable,sum))` calls with corresponding calls to `collapse::fsum`.

If you find this modfication helpful, you could directly use the ols.R file there (it is based on your newest dfadjust version downloaded today from Github) and just need to add the collapse package in your DESCRIPTION file as import or dependency.

PS: If I understand correctly, there is not yet any direct support for fixed effects (e.g. for `fixest` models) in `dfadjust`. But do you have any econometric intuition whether the resulting standard errors are still fine if I would just manually perform a within transformation on my data set, then run `lm` on the transformed data and then call `dfadjustSE`? In the few examples, I have run so far, SE after within transformation, seem to slightly differ from the SE using the dummy approach, but the differences seem quite small.

**Comment by skranz** [comment]
Sorry, just realized today that your package has a great Vignette which describes with an example how one can deal with fixed effects (and also nicely explains the amazing QR decomposition magic going on in the code). So speed gains from my proposed change will likely often not be too large, but perhaps still sometimes substantial.

I also updated my test package `dfadjustFaster` and created the `ols2.R` file. In addition to the changes described above, I added an argument `for_coefs` that allows to specify for which coefficients everything shall be computed. E.g. both calls below yield the same output:

```
dfadjustSE(r1, clustervar=d1$cl, ell=c(0, 1, rep(0, r1$rank-2)))
dfadjustSE(r1, clustervar=d1$cl, for_coefs = 2)
``` 
But unlike `ell`, the argument `for_coefs` allows to specify multiple coefficients, e.g.
```
dfadjustSE(r1, clustervar=d1$cl, for_coefs = 1:3)
```
That can be more convenient and faster than repeatedly running `dfadjustSE` with 3 different `ell` arguments.

**Comment by skranz** [comment]
I added one more feature in  https://github.com/skranz/dfadjustFaster :  a new argument `inv_mode`. If "K" then behavior is as in `dfadjust`:  for each cluster perform eigenvalue decomposition of the K x K  matrix Qs'Qs. If "n_s" then for each cluster s perform the eigenvalue decomposition instead for the n_s x n_s matrix I-QsQs', where n_s is the number of rows in cluster s. If `inv_mode = "min"` check for each cluster  whether K or n_s is smaller and use the smaller matrix. For backward compatibility the default is `inv_mode  = "K"`, but using "min" optimizes for speed.

Having looked at a few replication packages, the case that n_s < K for many clusters is actual not as rare as one might think, in particular if there are fixed effects estimated via LSDV. (I am still not sure whether it is appropriate to just cancel out the FE via within transformation and apply dfadjust on the demeaned variables.) Below is a simulation that confirms that all modes of `inv_mode` lead the same results, but at different computation times:

```r
# Example with fe
# comparing different inv_mode options

N = 10000
S = 500 # num_cluster
K = 200 # num_x
num_fe = 200
fe_vals = rnorm(num_fe)
fe_int = sample(1:num_fe,N, replace=TRUE)
fe_val = fe_vals[fe_int]

library(dplyr)
```

```r
dat <- tibble(
  x1=rnorm(N,0,1)+fe_val,
  x2=rnorm(N,0,1)+x1,
  cl = as.factor(sample(1:S, N, replace=TRUE, prob = (1:S)^20)),
  #cl = as.factor(rep(1:S, each = N/S)),
  fe = as.factor(fe_int),
  y = 0*x1 + 0*x2 + fe_val + rnorm(N, 0,1)
)
dat = arrange(dat, cl)
sort(table(dat$cl))
```

```
## 
## 335 346 352 360 364 366 369 371 375 376 377 380 393 402 345 356 359 374 383 384 
##   1   1   1   1   1   1   1   1   1   1   1   1   1   1   2   2   2   2   2   2 
## 390 391 400 357 372 382 385 386 387 395 396 398 399 401 378 392 394 397 407 408 
##   2   2   2   3   3   3   3   3   3   3   3   3   3   3   4   4   4   4   4   4 
## 388 403 405 409 414 406 418 404 411 416 423 424 412 413 417 419 422 429 420 421 
##   5   6   6   7   7   8   8   9   9   9   9  10  11  12  12  12  12  12  13  13 
## 425 427 410 434 415 432 433 426 428 431 430 435 438 440 437 445 442 447 436 444 
##  13  13  14  14  15  15  15  16  17  18  22  25  30  30  31  32  33  33  37  37 
## 441 446 439 450 443 452 448 449 453 459 451 457 456 454 455 458 460 462 461 465 
##  38  38  42  43  44  48  51  55  55  62  65  65  66  68  68  70  80  88  89  91 
## 463 471 464 466 468 467 470 469 472 475 474 476 478 477 473 479 480 481 486 482 
##  92  95 100 104 111 114 114 115 126 128 131 144 153 154 159 174 174 185 201 209 
## 483 484 485 489 487 488 490 491 493 494 496 492 495 498 500 497 499 
## 211 215 219 252 262 278 278 298 309 326 326 332 364 379 388 404 411
```

```r
library(dfadjustFaster)

# Spec 1: just add fe which is not nested in cl
reg = lm(y~x1+x2+fe, data=dat)
dfadjustSE(reg,for_coefs = 2:3, dat$cl,inv_mode="n_s", timing=TRUE)
```

```
## Time difference of 5.550497 secs
```

```
## 
## Coefficients:
##       Estimate      HC1 se      HC2 se     Adj. se       df    p-value
## x1 -0.02579377 0.010743285 0.010751923 0.011050633 44.74868 0.02066906
## x2  0.01063598 0.008973349 0.008994776 0.009251056 43.66271 0.24342177
```

```r
dfadjustSE(reg,for_coefs = 2:3, dat$cl,inv_mode="K", timing=TRUE)
```

```
## Time difference of 4.986795 secs
```

```
## 
## Coefficients:
##       Estimate      HC1 se      HC2 se     Adj. se       df    p-value
## x1 -0.02579377 0.010743285 0.010751923 0.011050633 44.74868 0.02066906
## x2  0.01063598 0.008973349 0.008994776 0.009251056 43.66271 0.24342177
```

```r
dfadjustSE(reg,for_coefs = 2:3, dat$cl,inv_mode="min",timing=TRUE)
```

```
## Time difference of 2.796929 secs
```

```
## 
## Coefficients:
##       Estimate      HC1 se      HC2 se     Adj. se       df    p-value
## x1 -0.02579377 0.010743285 0.010751923 0.011050633 44.74868 0.02066906
## x2  0.01063598 0.008973349 0.008994776 0.009251056 43.66271 0.24342177
```

```r
# Spec 2: cluster variable cl is also a fixed effect
reg = lm(y~x1+x2+fe+cl, data=dat)
dfadjustSE(reg,for_coefs = 2:3, dat$cl,inv_mode="n_s", timing=TRUE)
```

```
## Time difference of 6.984944 secs
```

```
## 
## Coefficients:
##        Estimate      HC1 se      HC2 se     Adj. se       df    p-value
## x1 -0.024680185 0.010855348 0.010787876 0.011093674 43.88105 0.02702734
## x2  0.009218437 0.009015457 0.008974077 0.009234686 42.86081 0.31007496
```

```r
dfadjustSE(reg,for_coefs = 2:3, dat$cl,inv_mode="K", timing=TRUE)
```

```
## Time difference of 17.71424 secs
```

```
## 
## Coefficients:
##        Estimate      HC1 se      HC2 se     Adj. se       df    p-value
## x1 -0.024680185 0.010855348 0.010787876 0.011093674 43.88105 0.02702734
## x2  0.009218437 0.009015457 0.008974077 0.009234686 42.86081 0.31007496
```

```r
dfadjustSE(reg,for_coefs = 2:3, dat$cl,inv_mode="min",timing=TRUE)
```

```
## Time difference of 6.393841 secs
```

```
## 
## Coefficients:
##        Estimate      HC1 se      HC2 se     Adj. se       df    p-value
## x1 -0.024680185 0.010855348 0.010787876 0.011093674 43.88105 0.02702734
## x2  0.009218437 0.009015457 0.008974077 0.009234686 42.86081 0.31007496
```

**Comment by kolesarm** [comment]
Sebastian:

Sorry first of all for the slow response, it's been a busy semester.

Thank you for these suggestions, they are fanastic! I have added you as a contributor to the package, since these are such useful suggestions.

I was not aware of the `collapse` package. The latest github version now uses `collapse::fsum` as you suggest, which does appear to speed it up noticeably. I also allow the user to specify the subset of regressors of interest by using the `ell` argument, e.g.:
```
x <- sin(1:100)
y <- tan(100:1)
r <- lm(y~x+I(x^2))
## not interested in intercept
dfadjustSE(r, ell=c(2,3))
## if length of ell equals covariate dimension, do inference on ell'beta, in this case second coefficient:
dfadjustSE(r, ell=c(0,1,0))
```
The CRAN version will also be updated shortly.

I didn't currently implement your last suggestion regarding `inv_mode`, to keep the interface and code simpler.

**Comment by skranz** [comment]
Hi Michal, thanks for implementing the suggestions and for your kind words. 

In case your are interested: Meanwhile I got some further insights from a first working paper version that studies different forms of heteroskedasticity robust standard errors using a large Monte-Carlo study based on real world regressions from 155 reproduction packages: https://arxiv.org/abs/2411.14763

Overall, HC2 with BM degree of freedom correction performs very well and outperforms HC3, HC4 and wild bootstrap. Yet, in 15,6% of regressions at least one observation i has a leverage of h_i=1. The Monte-Carlo analysis in Section 3 suggests that your current treatment of those cases, i.e. setting 1/(1-h_i)=0 if h_i=1 does not perform as well, as simply omitting observations with h_i=1, i.e. also omitting them from the denominator, not only setting them 0 in the numerator. The paper also suggests an alternative degree of freedom correction based on partial leverages, which also works well.

I am currently working on a similar working paper for cluster-robust inference. The tentative Monte-Carlo results suggest that HC2 with BM degree of freedoms works very well in cases where each cluster-specific projection matrix M_g = I - X_g (X'X)^-1 X_g' can be inverted. Yet, in cases where M_g cannot be inverted and a generalized Moore-Penrose inverse is used, performance seems on average fairly poor. Currently wild bootstrap performs substantially better in those cases. I don't know a simple remedy like for the HC case where one could simply omit all observations with h_i=1, since for the case of cluster-specific fixed effects essentially all clusters face the non-invertibility problem. (I plan to check out performance when simply absorbing the cluster specific fixed effects, though.)

Below are screenshots of the corresponding Monte-Carlo results (similar structure as in the working paper linked above):

### All M_g invertible
![image](https://github.com/user-attachments/assets/0dbd1c46-0225-411d-8c5b-b5e90b4d4040)
 
### Cases with at least one non-invertible M_g

![image](https://github.com/user-attachments/assets/03a9ac60-5c20-4145-9d68-f84e808b5885)

**Comment by kolesarm** [comment]
Thanks for sharing this work -- let me reply via email
